
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://server-ip:port/loki/api/v1/push

scrape_configs:
  - job_name: nginx_access_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx_access
          __path__: /var/log/nginx/access.log

  - job_name: nginx_error_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx_error
          __path__: /var/log/nginx/error.log

  - job_name: your-file_io_access_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: your-name_io_access
          __path__: /var/log/nginx/your-file.io_access.log

  - job_name: your-file_io_error_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: your-name_io_error
          __path__: /var/log/nginx/your-file.io_error.log
